/* Generated by bun run docs:generate. */
export const sitemap = {
  "data": {
    "Overview": {
      prefix: "/solid/overview/",
      pages: [
        {
          title: "Quick Start",
          path: "/solid/overview/quick-start"
        },
        {
          title: "About",
          path: "/solid/overview/about"
        },
        {
          title: "Accessibility",
          path: "/solid/overview/accessibility"
        },
        {
          title: "Releases",
          path: "/solid/overview/releases"
        },
        {
          title: "Community",
          path: "/solid/overview/community"
        }
      ]
    },
    "Handbook": {
      prefix: "/solid/handbook/",
      pages: [
        {
          title: "Styling",
          path: "/solid/handbook/styling"
        },
        {
          title: "Forms",
          path: "/solid/handbook/forms"
        },
        {
          title: "Composition",
          path: "/solid/handbook/composition"
        },
        {
          title: "Typescript",
          path: "/solid/handbook/typescript"
        },
        {
          title: "Customization",
          path: "/solid/handbook/customization"
        },
        {
          title: "Animation",
          path: "/solid/handbook/animation"
        }
      ]
    },
    "Components": {
      prefix: "/solid/components/",
      pages: [
        {
          title: "Scroll Area",
          path: "/solid/components/scroll-area"
        },
        {
          title: "Switch",
          path: "/solid/components/switch"
        },
        {
          title: "Select",
          path: "/solid/components/select"
        },
        {
          title: "Dialog",
          path: "/solid/components/dialog"
        },
        {
          title: "Preview Card",
          path: "/solid/components/preview-card"
        },
        {
          title: "Tooltip",
          path: "/solid/components/tooltip"
        },
        {
          title: "Progress",
          path: "/solid/components/progress"
        },
        {
          title: "OTP Field",
          path: "/solid/components/otp-field"
        },
        {
          title: "Avatar",
          path: "/solid/components/avatar"
        },
        {
          title: "Combobox",
          path: "/solid/components/combobox"
        },
        {
          title: "Tabs",
          path: "/solid/components/tabs"
        },
        {
          title: "Radio",
          path: "/solid/components/radio"
        },
        {
          title: "Popover",
          path: "/solid/components/popover"
        },
        {
          title: "Fieldset",
          path: "/solid/components/fieldset"
        },
        {
          title: "Field",
          path: "/solid/components/field"
        },
        {
          title: "Collapsible",
          path: "/solid/components/collapsible"
        },
        {
          title: "Separator",
          path: "/solid/components/separator"
        },
        {
          title: "Accordion",
          path: "/solid/components/accordion"
        },
        {
          title: "Alert Dialog",
          path: "/solid/components/alert-dialog"
        },
        {
          title: "Input",
          path: "/solid/components/input"
        },
        {
          title: "Toggle Group",
          path: "/solid/components/toggle-group"
        },
        {
          title: "Checkbox",
          path: "/solid/components/checkbox"
        },
        {
          title: "Checkbox Group",
          path: "/solid/components/checkbox-group"
        },
        {
          title: "Form",
          path: "/solid/components/form"
        },
        {
          title: "Toolbar",
          path: "/solid/components/toolbar"
        },
        {
          title: "Button",
          path: "/solid/components/button"
        },
        {
          title: "Drawer",
          path: "/solid/components/drawer"
        },
        {
          title: "Slider",
          path: "/solid/components/slider"
        },
        {
          title: "Toast",
          path: "/solid/components/toast"
        },
        {
          title: "Menubar",
          path: "/solid/components/menubar"
        },
        {
          title: "Menu",
          path: "/solid/components/menu"
        },
        {
          title: "Toggle",
          path: "/solid/components/toggle"
        },
        {
          title: "Autocomplete",
          path: "/solid/components/autocomplete"
        },
        {
          title: "Number Field",
          path: "/solid/components/number-field"
        },
        {
          title: "Navigation Menu",
          path: "/solid/components/navigation-menu"
        },
        {
          title: "Meter",
          path: "/solid/components/meter"
        },
        {
          title: "Context Menu",
          path: "/solid/components/context-menu"
        }
      ]
    },
    "Utils": {
      prefix: "/solid/utils/",
      pages: [
        {
          title: "Direction Provider",
          path: "/solid/utils/direction-provider"
        },
        {
          title: "Csp Provider",
          path: "/solid/utils/csp-provider"
        },
        {
          title: "Use Render",
          path: "/solid/utils/use-render"
        },
        {
          title: "Merge Props",
          path: "/solid/utils/merge-props"
        }
      ]
    }
  }
};
