/* Generated by bun run docs:generate. */
export interface SitemapPage {
  title: string
  path: string
  tags?: string[]
  isNew?: boolean
  isPreview?: boolean
}

export interface SitemapSection {
  title?: string
  prefix?: string
  pages: SitemapPage[]
}

export interface Sitemap {
  data: Record<string, SitemapSection>
}

export const sitemap: Sitemap = {
  "data": {
    "Overview": {
      "prefix": "/solid/overview/",
      "pages": [
        {
          "title": "Quick start",
          "path": "./quick-start/page.mdx"
        },
        {
          "title": "Accessibility",
          "path": "./accessibility/page.mdx"
        },
        {
          "title": "Releases",
          "path": "./releases/page.mdx"
        },
        {
          "title": "Community",
          "path": "./community/page.mdx"
        },
        {
          "title": "About Base UI",
          "path": "./about/page.mdx"
        }
      ]
    },
    "Handbook": {
      "prefix": "/solid/handbook/",
      "pages": [
        {
          "title": "Styling",
          "path": "./styling/page.mdx"
        },
        {
          "title": "Animation",
          "path": "./animation/page.mdx"
        },
        {
          "title": "Composition",
          "path": "./composition/page.mdx"
        },
        {
          "title": "Customization",
          "path": "./customization/page.mdx"
        },
        {
          "title": "Forms",
          "path": "./forms/page.mdx"
        },
        {
          "title": "TypeScript",
          "path": "./typescript/page.mdx"
        },
        {
          "title": "llms.txt",
          "path": "/llms.txt",
          "tags": [
            "External"
          ]
        }
      ]
    },
    "Components": {
      "prefix": "/solid/components/",
      "pages": [
        {
          "title": "Accordion",
          "path": "./accordion/page.mdx"
        },
        {
          "title": "Alert Dialog",
          "path": "./alert-dialog/page.mdx"
        },
        {
          "title": "Autocomplete",
          "path": "./autocomplete/page.mdx"
        },
        {
          "title": "Avatar",
          "path": "./avatar/page.mdx"
        },
        {
          "title": "Button",
          "path": "./button/page.mdx"
        },
        {
          "title": "Checkbox",
          "path": "./checkbox/page.mdx"
        },
        {
          "title": "Checkbox Group",
          "path": "./checkbox-group/page.mdx"
        },
        {
          "title": "Collapsible",
          "path": "./collapsible/page.mdx"
        },
        {
          "title": "Combobox",
          "path": "./combobox/page.mdx"
        },
        {
          "title": "Context Menu",
          "path": "./context-menu/page.mdx"
        },
        {
          "title": "Dialog",
          "path": "./dialog/page.mdx"
        },
        {
          "title": "Drawer",
          "path": "./drawer/page.mdx"
        },
        {
          "title": "Field",
          "path": "./field/page.mdx"
        },
        {
          "title": "Fieldset",
          "path": "./fieldset/page.mdx"
        },
        {
          "title": "Form",
          "path": "./form/page.mdx"
        },
        {
          "title": "Input",
          "path": "./input/page.mdx"
        },
        {
          "title": "Menu",
          "path": "./menu/page.mdx"
        },
        {
          "title": "Menubar",
          "path": "./menubar/page.mdx"
        },
        {
          "title": "Meter",
          "path": "./meter/page.mdx"
        },
        {
          "title": "Navigation Menu",
          "path": "./navigation-menu/page.mdx"
        },
        {
          "title": "Number Field",
          "path": "./number-field/page.mdx"
        },
        {
          "title": "OTP Field",
          "path": "./otp-field/page.mdx"
        },
        {
          "title": "Popover",
          "path": "./popover/page.mdx"
        },
        {
          "title": "Preview Card",
          "path": "./preview-card/page.mdx"
        },
        {
          "title": "Progress",
          "path": "./progress/page.mdx"
        },
        {
          "title": "Radio",
          "path": "./radio/page.mdx"
        },
        {
          "title": "Scroll Area",
          "path": "./scroll-area/page.mdx"
        },
        {
          "title": "Select",
          "path": "./select/page.mdx"
        },
        {
          "title": "Separator",
          "path": "./separator/page.mdx"
        },
        {
          "title": "Slider",
          "path": "./slider/page.mdx"
        },
        {
          "title": "Switch",
          "path": "./switch/page.mdx"
        },
        {
          "title": "Tabs",
          "path": "./tabs/page.mdx"
        },
        {
          "title": "Toast",
          "path": "./toast/page.mdx"
        },
        {
          "title": "Toggle",
          "path": "./toggle/page.mdx"
        },
        {
          "title": "Toggle Group",
          "path": "./toggle-group/page.mdx"
        },
        {
          "title": "Toolbar",
          "path": "./toolbar/page.mdx"
        },
        {
          "title": "Tooltip",
          "path": "./tooltip/page.mdx"
        }
      ]
    },
    "Utils": {
      "prefix": "/solid/utils/",
      "pages": [
        {
          "title": "CSP Provider",
          "path": "./csp-provider/page.mdx"
        },
        {
          "title": "Direction Provider",
          "path": "./direction-provider/page.mdx"
        },
        {
          "title": "mergeProps",
          "path": "./merge-props/page.mdx"
        },
        {
          "title": "useRender",
          "path": "./use-render/page.mdx"
        }
      ]
    }
  }
}
