import { vi } from "vitest"
import { getTicks, GetTicksInput } from "../../src/cartesian/getTicks"
import { CartesianTickItem, TickItem } from "../../src/util/types"

const EXAMPLE_INPUT: GetTicksInput = {
	angle: undefined,
	interval: "preserveStart" as const,
	minTickGap: 5,
	orientation: "bottom" as const,
	tick: true,
	tickFormatter: undefined,
	ticks: [
		{ coordinate: 50, index: 0, offset: 0, value: "10" },
		{ coordinate: 100, index: 1, offset: 0, value: "1000" },
		{ coordinate: 150, index: 2, offset: 0, value: "20" },
		{ coordinate: 200, index: 3, offset: 0, value: "40" },
		{ coordinate: 250, index: 4, offset: 0, value: "90" },
		{ coordinate: 300, index: 5, offset: 0, value: "A" },
	],
	unit: "",
	viewBox: { height: 500, width: 500, x: 0, y: 0 },
}

vi.mock("../../src/util/DOMUtils", () => ({
	// We mock string size measurement, because getStringSize else returns 0 in these tests.
	getStringSize: vi.fn((text: string) => ({ height: 12, width: text.length })),
}))

// These tests have been generated by merely documenting existing behaviour.
// They will be used to verify that any refactoring does not break the existing behaviour.
describe("getTicks", () => {
	describe("ticks are always shown if there is space", () => {
		test("preserveEnd", () => {
			const input: GetTicksInput = { ...EXAMPLE_INPUT, interval: "preserveEnd" as const }

			const result = getTicks(input)

			expect(result).toEqual([
				{ coordinate: 50, index: 0, isShow: true, offset: 0, tickCoord: 50, value: "10" },
				{ coordinate: 100, index: 1, isShow: true, offset: 0, tickCoord: 100, value: "1000" },
				{ coordinate: 150, index: 2, isShow: true, offset: 0, tickCoord: 150, value: "20" },
				{ coordinate: 200, index: 3, isShow: true, offset: 0, tickCoord: 200, value: "40" },
				{ coordinate: 250, index: 4, isShow: true, offset: 0, tickCoord: 250, value: "90" },
				{ coordinate: 300, index: 5, isShow: true, offset: 0, tickCoord: 300, value: "A" },
			])
		})
		test("preserveStart", () => {
			const input = { ...EXAMPLE_INPUT, interval: "preserveStart" as const }

			const result = getTicks(input)

			expect(result).toEqual([
				{ coordinate: 50, index: 0, isShow: true, offset: 0, tickCoord: 50, value: "10" },
				{ coordinate: 100, index: 1, isShow: true, offset: 0, tickCoord: 100, value: "1000" },
				{ coordinate: 150, index: 2, isShow: true, offset: 0, tickCoord: 150, value: "20" },
				{ coordinate: 200, index: 3, isShow: true, offset: 0, tickCoord: 200, value: "40" },
				{ coordinate: 250, index: 4, isShow: true, offset: 0, tickCoord: 250, value: "90" },
				{ coordinate: 300, index: 5, isShow: true, offset: 0, tickCoord: 300, value: "A" },
			])
		})
	})
	describe("ticks are shown if there is space when displayed at an angle", () => {
		test("preserveEnd", () => {
			const ticks: ReadonlyArray<TickItem> = [
				{ coordinate: 50, index: 0, offset: 0, value: "100_000_000_000_000" },
				{ coordinate: 70, index: 1, offset: 0, value: "200_000_000_000_000" },
				{ coordinate: 90, index: 2, offset: 0, value: "300_000_000_000_000" },
				{ coordinate: 110, index: 3, offset: 0, value: "400_000_000_000_000" },
				{ coordinate: 130, index: 4, offset: 0, value: "500_000_000_000_000" },
				{ coordinate: 150, index: 5, offset: 0, value: "600_000_000_000_000" },
			]
			const input = { ...EXAMPLE_INPUT, interval: "preserveEnd" as const, ticks }

			// Only 3 ticks are shown
			expect(getTicks(input)).toEqual([
				{
					coordinate: 70,
					index: 1,
					isShow: true,
					offset: 0,
					tickCoord: 70,
					value: "200_000_000_000_000",
				},
				{
					coordinate: 110,
					index: 3,
					isShow: true,
					offset: 0,
					tickCoord: 110,
					value: "400_000_000_000_000",
				},
				{
					coordinate: 150,
					index: 5,
					isShow: true,
					offset: 0,
					tickCoord: 150,
					value: "600_000_000_000_000",
				},
			])

			const angledInput = { ...input, angle: 60 }

			// But at an angle we can fit all ticks
			expect(getTicks(angledInput)).toEqual([
				{
					coordinate: 50,
					index: 0,
					isShow: true,
					offset: 0,
					tickCoord: 50,
					value: "100_000_000_000_000",
				},
				{
					coordinate: 70,
					index: 1,
					isShow: true,
					offset: 0,
					tickCoord: 70,
					value: "200_000_000_000_000",
				},
				{
					coordinate: 90,
					index: 2,
					isShow: true,
					offset: 0,
					tickCoord: 90,
					value: "300_000_000_000_000",
				},
				{
					coordinate: 110,
					index: 3,
					isShow: true,
					offset: 0,
					tickCoord: 110,
					value: "400_000_000_000_000",
				},
				{
					coordinate: 130,
					index: 4,
					isShow: true,
					offset: 0,
					tickCoord: 130,
					value: "500_000_000_000_000",
				},
				{
					coordinate: 150,
					index: 5,
					isShow: true,
					offset: 0,
					tickCoord: 150,
					value: "600_000_000_000_000",
				},
			])
		})
		test("preserveStart", () => {
			const ticks: ReadonlyArray<TickItem> = [
				{ coordinate: 50, index: 0, offset: 0, value: "100_000_000_000_000" },
				{ coordinate: 70, index: 1, offset: 0, value: "200_000_000_000_000" },
				{ coordinate: 90, index: 2, offset: 0, value: "300_000_000_000_000" },
				{ coordinate: 110, index: 3, offset: 0, value: "400_000_000_000_000" },
				{ coordinate: 130, index: 4, offset: 0, value: "500_000_000_000_000" },
				{ coordinate: 150, index: 5, offset: 0, value: "600_000_000_000_000" },
			]
			const input = { ...EXAMPLE_INPUT, interval: "preserveStart" as const, ticks }

			// Only 3 ticks are shown
			expect(getTicks(input)).toEqual([
				{
					coordinate: 50,
					index: 0,
					isShow: true,
					offset: 0,
					tickCoord: 50,
					value: "100_000_000_000_000",
				},
				{
					coordinate: 90,
					index: 2,
					isShow: true,
					offset: 0,
					tickCoord: 90,
					value: "300_000_000_000_000",
				},
				{
					coordinate: 130,
					index: 4,
					isShow: true,
					offset: 0,
					tickCoord: 130,
					value: "500_000_000_000_000",
				},
			])

			const angledInput = { ...input, angle: 60 }

			// But at an angle we can fit all ticks
			expect(getTicks(angledInput)).toEqual([
				{
					coordinate: 50,
					index: 0,
					isShow: true,
					offset: 0,
					tickCoord: 50,
					value: "100_000_000_000_000",
				},
				{
					coordinate: 70,
					index: 1,
					isShow: true,
					offset: 0,
					tickCoord: 70,
					value: "200_000_000_000_000",
				},
				{
					coordinate: 90,
					index: 2,
					isShow: true,
					offset: 0,
					tickCoord: 90,
					value: "300_000_000_000_000",
				},
				{
					coordinate: 110,
					index: 3,
					isShow: true,
					offset: 0,
					tickCoord: 110,
					value: "400_000_000_000_000",
				},
				{
					coordinate: 130,
					index: 4,
					isShow: true,
					offset: 0,
					tickCoord: 130,
					value: "500_000_000_000_000",
				},
				{
					coordinate: 150,
					index: 5,
					isShow: true,
					offset: 0,
					tickCoord: 150,
					value: "600_000_000_000_000",
				},
			])
		})
	})
	describe("The interval is respected", () => {
		const viewBoxWithSmallWidth = { height: 500, width: 30, x: 0, y: 0 }

		test.each([
			[
				(EXAMPLE_INPUT.ticks?.length ?? 0) + 1,
				[{ coordinate: 50, index: 0, offset: 0, value: "10" }],
			],
			[
				2,
				[
					{ coordinate: 50, index: 0, offset: 0, value: "10" },
					{ coordinate: 200, index: 3, offset: 0, value: "40" },
				],
			],
			[
				1,
				[
					{ coordinate: 50, index: 0, offset: 0, value: "10" },
					{ coordinate: 150, index: 2, offset: 0, value: "20" },
					{ coordinate: 250, index: 4, offset: 0, value: "90" },
				],
			],
			[
				0,
				[
					{ coordinate: 50, index: 0, offset: 0, value: "10" },
					{ coordinate: 100, index: 1, offset: 0, value: "1000" },
					{ coordinate: 150, index: 2, offset: 0, value: "20" },
					{ coordinate: 200, index: 3, offset: 0, value: "40" },
					{ coordinate: 250, index: 4, offset: 0, value: "90" },
					{ coordinate: 300, index: 5, offset: 0, value: "A" },
				],
			],
			[
				"preserveStartEnd" as const,
				[
					{
						coordinate: 300,
						index: 5,
						isShow: true,
						offset: 0,
						tickCoord: 29.5,
						value: "A",
					},
				],
			],
			["preserveStart" as const, []],
			[
				"preserveEnd" as const,
				[
					{
						coordinate: 300,
						index: 5,
						isShow: true,
						offset: 0,
						tickCoord: 29.5,
						value: "A",
					},
				],
			],
			["equidistantPreserveStart" as const, [{ coordinate: 50, index: 0, offset: 0, value: "10" }]],
			[-1, []],
			[
				undefined,
				[{ coordinate: 300, index: 5, isShow: true, offset: 0, tickCoord: 29.5, value: "A" }],
			],
		])(`interval %s works`, (interval, expectedResult) => {
			const input = {
				...EXAMPLE_INPUT,
				interval,
				viewBox: viewBoxWithSmallWidth,
			}

			const result = getTicks(input)

			expect(result).toEqual(expectedResult)
		})
	})
	describe("Equidistant ticks are shown depending on label width and space between ticks", () => {
		test.each([
			// With enough space, all ticks are shown.
			[["11111111111111", "2", "3", "4"], 20, ["11111111111111", "2", "3", "4"]],
			[["1", "22222222222222", "3", "4"], 20, ["1", "22222222222222", "3", "4"]],
			[["1", "2", "33333333333333", "4"], 20, ["1", "2", "33333333333333", "4"]],
			[["1", "2", "3", "44444444444444"], 20, ["1", "2", "3", "44444444444444"]],

			// If not enough space is available we show only every nTH.
			[["11111111111111", "2", "3", "4"], 5, ["11111111111111", "4"]], // every 3rd
			[["1", "22222222222222", "3", "4"], 5, ["1", "3"]], // every 2nd
			[["1", "2", "33333333333333", "4"], 5, ["1", "4"]], // every 3rd
			[["1", "2", "3", "44444444444444"], 5, ["1", "3"]], // every 2nd

			// If not enough space is available at all, we only show the first tick.
			[["11111111111111", "2", "3", "4"], 1, ["11111111111111"]],
			[["1", "22222222222222", "3", "4"], 1, ["1"]],
			[["1", "2", "33333333333333", "4"], 1, ["1"]],
			[["1", "2", "3", "44444444444444"], 1, ["1"]],
		])(
			`equidistantPreserveStart spaces nicely for %s and tick step of %s`,
			(tickValues, tickWidthStep, expectedResult) => {
				const ticks: ReadonlyArray<TickItem> = tickValues.map(
					(value, index): TickItem => ({
						coordinate: tickWidthStep * (index + 1),
						index,
						offset: 0,
						value,
					}),
				)
				const input = {
					...EXAMPLE_INPUT,
					interval: "equidistantPreserveStart" as const,
					ticks,
				}

				const resultingTickValues = (getTicks(input) as CartesianTickItem[]).map(
					(tick) => tick.value,
				)

				expect(resultingTickValues).toEqual(expectedResult)
			},
		)
	})
})
