// node profile.mjs <lib> <scenario> [dir]  -> self-time by function for mount, heap allocation sampling
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
import { fileURLToPath } from 'node:url'; import { chromium } from 'playwright';
const here = path.dirname(fileURLToPath(import.meta.url));
const builds = path.resolve(here, '../../../../.tmp/grunt/bench-builds');
const resultsDir = path.resolve(here, '../../../../.tmp/grunt/bench-results');
const [lib, scenario, dir = 'dist-dev', setup = '', measured = ''] = process.argv.slice(2);
const SETUP = setup || '';
const MEASURE = measured || `lib.mount('${scenario}'); lib.unmount()`;
const server = http.createServer((req, res) => {
  const [l, ...rest] = req.url.split('?')[0].slice(1).split('/');
  const file = path.join(builds, l, dir, rest.join('/') || 'index.html');
  if (!fs.existsSync(file)) return res.writeHead(404).end();
  res.writeHead(200, { 'content-type': file.endsWith('.js') ? 'text/javascript' : 'text/html' });
  fs.createReadStream(file).pipe(res);
}).listen(0);
const browser = await chromium.launch({ args: ['--js-flags=--expose-gc'] });
const page = await browser.newPage();
await page.goto(`http://localhost:${server.address().port}/${lib}/`);
const cdp = await page.context().newCDPSession(page);
if (SETUP) await page.evaluate(SETUP);
for (let i = 0; i < 2; i++) await page.evaluate(MEASURE);
await cdp.send('Profiler.enable');
await cdp.send('Profiler.setSamplingInterval', { interval: 50 });
await cdp.send('HeapProfiler.enable');
await cdp.send('HeapProfiler.startSampling', { samplingInterval: 512 });
await cdp.send('Profiler.start');
for (let i = 0; i < 5; i++) await page.evaluate(MEASURE);
const { profile } = await cdp.send('Profiler.stop');
if (!SETUP) await page.evaluate(`lib.mount('${scenario}')`);
const { profile: heap } = await cdp.send('HeapProfiler.stopSampling');
const self = new Map(); const dt = profile.timeDeltas; const byId = new Map(profile.nodes.map(n => [n.id, n]));
profile.samples.forEach((id, i) => { const n = byId.get(id); const k = `${n.callFrame.functionName || '(anon)'}:${n.callFrame.lineNumber+1}`; self.set(k, (self.get(k) || 0) + (dt[i] || 0)); });
const total = [...self.values()].reduce((a, b) => a + b, 0);
console.log('CPU self time top 30 (ms over 5 mount+unmount):', (total/1000).toFixed(0));
[...self].sort((a, b) => b[1] - a[1]).slice(0, 30).forEach(([k, v]) => console.log((v/1000).toFixed(1).padStart(8), k));
const alloc = new Map();
const walk = (n) => { const k = `${n.callFrame.functionName || '(anon)'}:${n.callFrame.lineNumber+1}`; alloc.set(k, (alloc.get(k) || 0) + n.selfSize); n.children.forEach(walk); };
walk(heap.head);
console.log('\nHeap alloc (live, sampled) top 25 KB:');
[...alloc].sort((a, b) => b[1] - a[1]).slice(0, 25).forEach(([k, v]) => console.log((v/1024).toFixed(0).padStart(8), k));
await browser.close(); server.close();
