import { createMemo, Show, type JSX, type ParentProps } from "solid-js"
import { Collapsible } from "@solidports/base-ui/collapsible"
import { ScrollArea as BaseScrollArea } from "@solidports/base-ui/scroll-area"
import * as ScrollArea from "../ScrollArea"
import { highlightInline } from "../../syntax-highlighting/highlight"
import type { DemoFile } from "./useDemo"
import "./CodeHighlighting.css"

interface DemoCodeBlockProps {
  selectedFile: DemoFile | undefined
  selectedFileLines: number
  collapsibleOpen: boolean
  /** How many lines should the code block have to get collapsed instead of rendering fully */
  collapsibleLinesThreshold?: number
  collapsibleTriggerRef?: (el: HTMLElement | null | undefined) => void
  copyButton?: JSX.Element
}

/* Renders the highlighted code inline. Lives in the consumer (not useDemo) so the
   `<pre>`/`<code>` template participates in the parent component's hydration walk —
   creating it inside a memo broke hydration markers. */
function HighlightedCode(props: { file: DemoFile | undefined }) {
  const html = createMemo(() => {
    const file = props.file
    if (!file || !file.text) return ""
    return highlightInline(file.text, file.lang)
  })
  const lang = createMemo(() => props.file?.lang ?? "text")
  return (
    <pre class="shiki" data-language={lang()} style={{ "white-space": "pre", margin: "0" }}>
      {/* shiki output is trusted — generated by our own highlighter, not user input */}
      <code>
        <span class="frame" data-frame-type="focus" innerHTML={html()} />
      </code>
    </pre>
  )
}

function Root(props: ParentProps<{ closed?: boolean }>) {
  /* Upstream spreads keydown onto the ScrollArea root; Solid's ScrollArea.Root typings
     don't expose native div attrs directly, so catch the keydown on a wrapping div
     and still delegate rendering to BaseScrollArea via render-prop. */
  let rootEl: HTMLDivElement | undefined
  return (
    <div
      ref={(el) => (rootEl = el)}
      class="DemoCodeBlockRoot"
      data-closed={props.closed ? "" : undefined}
      tabIndex={-1}
      onKeyDown={(event) => {
        if (
          (event.ctrlKey || event.metaKey) &&
          String.fromCharCode(event.keyCode) === "A" &&
          !event.shiftKey &&
          !event.altKey
        ) {
          event.preventDefault()
          if (rootEl) window.getSelection()?.selectAllChildren(rootEl)
        }
      }}
    >
      <BaseScrollArea.Root>{props.children}</BaseScrollArea.Root>
    </div>
  )
}

function Source(props: { file: DemoFile | undefined }) {
  return (
    <div class="DemoSourceBrowser" data-language={props.file?.lang ?? "text"}>
      <HighlightedCode file={props.file} />
    </div>
  )
}

export function DemoCodeBlock(props: DemoCodeBlockProps) {
  const threshold = () => props.collapsibleLinesThreshold ?? 8
  const collapsed = () => props.selectedFileLines >= threshold() && !props.collapsibleOpen

  return (
    <Show
      when={props.selectedFileLines >= threshold()}
      fallback={
        <Root>
          <ScrollArea.Viewport>
            <Source file={props.selectedFile} />
          </ScrollArea.Viewport>
          <ScrollArea.Corner />
          <ScrollArea.Scrollbar orientation="vertical" />
          <ScrollArea.Scrollbar orientation="horizontal" />
          {props.copyButton}
        </Root>
      }
    >
      <div class="DemoCodeBlockCollapsible">
        <Root closed={collapsed()}>
          <ScrollArea.Viewport
            aria-hidden={collapsed()}
            data-closed={collapsed() ? "" : undefined}
            class="DemoCodeBlockViewport"
          >
            <Source file={props.selectedFile} />
          </ScrollArea.Viewport>
          <Show when={props.collapsibleOpen}>
            <ScrollArea.Corner />
            <ScrollArea.Scrollbar orientation="vertical" />
            <ScrollArea.Scrollbar orientation="horizontal" />
          </Show>
          {props.copyButton}
          <Collapsible.Trigger
            class="DemoCollapseButton"
            data-sticky={props.collapsibleOpen ? "" : undefined}
          >
            <span
              ref={props.collapsibleTriggerRef}
              class="DemoCollapseButtonVisual"
            >
              {props.collapsibleOpen ? "Hide code" : "Show code"}
            </span>
          </Collapsible.Trigger>
        </Root>
      </div>
    </Show>
  )
}
