import { createMemo, Show, type ParentProps } from "solid-js"
import { Collapsible } from "@solidports/base-ui/collapsible"
import { ScrollArea as BaseScrollArea } from "@solidports/base-ui/scroll-area"
import * as ScrollArea from "../ScrollArea"
import { highlightInline } from "../../syntax-highlighting/highlight"
import type { DemoFile } from "./useDemo"
import "./CodeHighlighting.css"

interface DemoCodeBlockProps {
  selectedFile: DemoFile | undefined
  selectedFileLines: number
  collapsibleOpen: boolean
  /** How many lines should the code block have to get collapsed instead of rendering fully */
  collapsibleLinesThreshold?: number
  collapsibleTriggerRef?: (el: HTMLButtonElement | null | undefined) => void
  /** Don't show a preview of the collapse code. */
  compact: boolean
}

/* Renders the highlighted code inline. Lives in the consumer (not useDemo) so the
   `<pre>`/`<code>` template participates in the parent component's hydration walk —
   creating it inside a memo broke hydration markers. */
function HighlightedCode(props: { file: DemoFile | undefined }) {
  const html = createMemo(() => {
    const file = props.file
    if (!file || !file.text) return ""
    return highlightInline(file.text, file.lang)
  })
  const lang = createMemo(() => props.file?.lang ?? "text")
  return (
    <pre class="shiki" data-language={lang()}>
      {/* shiki output is trusted — generated by our own highlighter, not user input */}
      {/* eslint-disable-next-line solid/no-innerhtml */}
      <code innerHTML={html()} />
    </pre>
  )
}

function Root(props: ParentProps) {
  /* Upstream spreads keydown onto the ScrollArea root; Solid's ScrollArea.Root typings
     don't expose native div attrs directly, so catch the keydown on a wrapping div
     and still delegate rendering to BaseScrollArea via render-prop. */
  let rootEl: HTMLDivElement | undefined
  return (
    <div
      ref={(el) => (rootEl = el)}
      class="DemoCodeBlockRoot"
      tabIndex={-1}
      onKeyDown={(event) => {
        if (
          (event.ctrlKey || event.metaKey) &&
          String.fromCharCode(event.keyCode) === "A" &&
          !event.shiftKey &&
          !event.altKey
        ) {
          event.preventDefault()
          if (rootEl) window.getSelection()?.selectAllChildren(rootEl)
        }
      }}
    >
      <BaseScrollArea.Root>{props.children}</BaseScrollArea.Root>
    </div>
  )
}

export function DemoCodeBlock(props: DemoCodeBlockProps) {
  const threshold = () => props.collapsibleLinesThreshold ?? 12

  return (
    <Show
      when={props.selectedFileLines >= threshold()}
      fallback={
        <Root>
          <ScrollArea.Viewport>
            <div class="DemoSourceBrowser" data-language={props.selectedFile?.lang ?? "text"}>
              <HighlightedCode file={props.selectedFile} />
            </div>
          </ScrollArea.Viewport>
          <ScrollArea.Corner />
          <ScrollArea.Scrollbar orientation="vertical" />
          <ScrollArea.Scrollbar orientation="horizontal" />
        </Root>
      }
    >
      <>
        {/* Solid Collapsible.Panel collapses to height 0 — drop it and let CSS .DemoCodeBlockViewport[data-closed] cap height for the preview. Trigger toggles the parent Collapsible.Root open state. */}
        <Root>
          <ScrollArea.Viewport
            aria-hidden={!props.collapsibleOpen}
            data-closed={props.collapsibleOpen ? undefined : ""}
            class="DemoCodeBlockViewport"
          >
            <div class="DemoSourceBrowser" data-language={props.selectedFile?.lang ?? "text"}>
              <HighlightedCode file={props.selectedFile} />
            </div>
          </ScrollArea.Viewport>
          <Show when={props.collapsibleOpen}>
            <ScrollArea.Corner />
            <ScrollArea.Scrollbar orientation="vertical" />
            <ScrollArea.Scrollbar orientation="horizontal" />
          </Show>
        </Root>

        <Collapsible.Trigger
          ref={props.collapsibleTriggerRef}
          class="DemoCollapseButton"
          data-sticky={props.collapsibleOpen ? "" : undefined}
        >
          {props.collapsibleOpen ? "Hide" : "Show"} code
        </Collapsible.Trigger>
      </>
    </Show>
  )
}
