/* eslint-disable import/no-cycle */
import type { JSX } from "solid-js"
import { createEffect, createMemo, onCleanup, Show } from "solid-js"
import { produce } from "solid-js/store"
import { clsx } from "clsx"
import {
	AxisDomainTypeInput,
	AxisInterval,
	AxisTick,
	RenderableAxisProps,
	PresentationAttributesAdaptChildEvent,
	Size,
	AxisDomain,
	ScaleType,
	EvaluatedAxisDomainType,
	TickProp,
	YAxisTickContentProps,
} from "../util/types"
import { CartesianAxis, CartesianAxisRef, defaultCartesianAxisProps } from "./CartesianAxis"
import type {
	YAxisOrientation,
	YAxisPadding,
	YAxisSettings,
	YAxisWidth,
} from "../state/cartesianAxisSlice"
import { useChartStore } from "../state/RechartsStoreContext"
import { useContext } from "solid-js"
import { RechartsStateContext } from "../state/_solid/RechartsStateContext"
import {
	implicitYAxis,
	selectTicksOfAxis,
	selectYAxisPosition,
	selectYAxisSettingsNoDefaults,
	selectYAxisSize,
} from "../state/selectors/axisSelectors"
import { useAxisViewBox } from "../state/hooks/useChartSelectors"
import { useIsPanorama } from "../context/PanoramaContext"
import { isLabelContentAFunction } from "../component/Label"
import { RequiresDefaultProps, resolveDefaultProps } from "../util/resolveDefaultProps"
import { CustomScaleDefinition } from "../util/scale/CustomScaleDefinition"
import { useCartesianChartLayout } from "../context/chartLayoutContext"
import { getAxisTypeBasedOnLayout } from "../util/getAxisTypeBasedOnLayout"

interface YAxisProps<DataPointType = unknown, DataValueType = unknown> extends Omit<
	RenderableAxisProps<DataPointType, DataValueType>,
	"axisLine" | "domain" | "scale" | "tick"
> {
	/**
	 * Determines how the axis line is drawn. Options:
	 * - `true`: the axis line is drawn with default props;
	 * - `false`: the axis line is not visible;
	 * - `object`: passed as props to SVG `<line>` element representing the axis line.
	 *
	 * @example <YAxis axisLine={false} />
	 * @example <YAxis axisLine={{ stroke: 'red', strokeWidth: 2 }} />
	 * @defaultValue true
	 */
	axisLine?: boolean | JSX.LineSVGAttributes<SVGLineElement>
	/**
	 * The type of axis.
	 *
	 * `category`: Treats data as distinct values.
	 * Each value is in the same distance from its neighbors, regardless of their actual numeric difference.
	 *
	 * `number`: Treats data as continuous range.
	 * Values that are numerically closer are placed closer together on the axis.
	 *
	 * `auto`: the type is inferred based on the chart layout.
	 *
	 * @defaultValue number
	 */
	type?: AxisDomainTypeInput
	/**
	 * Specify the domain of axis when the axis is a number axis.
	 *
	 * If undefined, then the domain is calculated based on the data and dataKeys.
	 *
	 * The length of domain should be 2, and we will validate the values in domain.
	 *
	 * Each element in the array can be a number, 'auto', 'dataMin', 'dataMax', a string like 'dataMin - 20', 'dataMax + 100',
	 * or a function that accepts a single argument and returns a number.
	 *
	 * If any element of domain is set to be 'auto', comprehensible scale ticks will be calculated, and the final domain of axis is generated by the ticks.
	 * If a function, receives '[dataMin, dataMax]', and must return a computed domain as '[min, max]'.
	 *
	 * @example <YAxis type="number" domain={['dataMin', 'dataMax']} />
	 * @example <YAxis type="number" domain={[0, 'dataMax']} />
	 * @example <YAxis type="number" domain={['auto', 'auto']} />
	 * @example <YAxis type="number" domain={[0, 'dataMax + 1000']} />
	 * @example <YAxis type="number" domain={['dataMin - 100', 'dataMax + 100']} />
	 * @example <YAxis type="number" domain={[dataMin => (0 - Math.abs(dataMin)), dataMax => (dataMax * 2)]} />
	 * @example <YAxis type="number" domain={([dataMin, dataMax]) => { const absMax = Math.max(Math.abs(dataMin), Math.abs(dataMax)); return [-absMax, absMax]; }} />
	 * @example <YAxis type="number" domain={[0, 100]} allowDataOverflow />
	 */
	domain?: AxisDomain
	/**
	 * Scale function determines how data values are mapped to visual values.
	 * In other words, decided the mapping between data domain and coordinate range.
	 *
	 * If undefined, or 'auto', the scale function is created internally according to the type of axis and data.
	 *
	 * You can define a custom scale, either as a string shortcut to a d3 scale, or as a complete scale definition object.
	 *
	 * @defaultValue auto
	 * @example <YAxis scale="log" />
	 * @example
	 * import { scaleLog } from 'd3-scale';
	 * const scale = scaleLog().base(Math.E);
	 * <YAxis scale={scale} />
	 */
	scale?:
		| ScaleType
		| CustomScaleDefinition
		| CustomScaleDefinition<string>
		| CustomScaleDefinition<number>
		| CustomScaleDefinition<Date>
	/**
	 * Unique ID that represents this YAxis.
	 * Required when there are multiple YAxes.
	 *
	 * @defaultValue 0
	 */
	yAxisId?: string | number
	/**
	 * Defines how the individual label text is rendered.
	 * This controls the settings for individual ticks; on a typical axis, there are multiple ticks, depending on your data.
	 *
	 * If you want to customize the overall axis label, use the `label` prop instead.
	 *
	 * Options:
	 * - `false`: Do not render any tick labels.
	 * - `true`: Render tick labels with default settings.
	 * - `object`: An object of props to be merged into the internally calculated tick props.
	 * - `ReactElement`: A custom React element to be used as the tick label.
	 * - `function`: A function that returns a React element for custom rendering of tick labels.
	 *
	 * @defaultValue true
	 */
	tick?: TickProp<YAxisTickContentProps>
	/**
	 * Ticks can be any type when the axis is the type of category
	 * Ticks must be numbers when the axis is the type of number
	 */
	ticks?: ReadonlyArray<AxisTick>
	/**
	 * Width of the axis in pixels.
	 * `auto` will attempt to resize the axis based on its content.
	 *
	 * @defaultValue 60
	 */
	width?: YAxisWidth
	/**
	 * If set true, flips ticks around the axis line, displaying the labels inside the chart instead of outside.
	 * @defaultValue false
	 */
	mirror?: boolean
	/**
	 * The orientation of axis.
	 * @defaultValue left
	 */
	orientation?: YAxisOrientation
	/**
	 * Axis padding is the distance between the edge of plot area and the first/last tick.
	 *
	 * @defaultValue {"top":0,"bottom":0}
	 */
	padding?: YAxisPadding
	/**
	 * The minimum gap between two adjacent tick labels
	 *
	 * @defaultValue 5
	 */
	minTickGap?: number
	/**
	 * If set 0, all the ticks will be shown. If set "preserveStart", "preserveEnd" or "preserveStartEnd",
	 * the ticks which is to be shown or hidden will be calculated automatically.
	 *
	 * @defaultValue preserveEnd
	 */
	interval?: AxisInterval
	/**
	 * The margin between tick line and tick.
	 */
	tickMargin?: number
}

export type Props = Omit<
	PresentationAttributesAdaptChildEvent<unknown, SVGElement>,
	"scale" | "ref"
> &
	YAxisProps

function SetYAxisSettings(
	props: Omit<YAxisSettings, "type"> & { type: AxisDomainTypeInput },
): null {
	const ctx = useChartStore()
	const stateCtx = useContext(RechartsStateContext)
	let prevSettings: YAxisSettings | null = null
	const evaluatedType = (): EvaluatedAxisDomainType | undefined => {
		/* eslint-disable-next-line solid/reactivity -- called only from inside createMemo below; reads are tracked through the call chain */
		const { type: typeFromProps, ..._ } = props
		return getAxisTypeBasedOnLayout(useCartesianChartLayout(), "yAxis", typeFromProps)
	}

	const settings = createMemo((): YAxisSettings | undefined => {
		const et = evaluatedType()
		if (et == null) {
			return undefined
		}
		/* eslint-disable-next-line solid/reactivity -- inside createMemo body; destructure is tracked */
		const { type: _t, ...restProps } = props
		return {
			...restProps,
			type: et,
		}
	})

	createEffect(() => {
		const s = settings()
		if (s == null) {
			return
		}
		stateCtx?.setState("cartesianAxes", "yAxis", String(s.id), { settings: s })
		/* Legacy compat shim — keeps state.cartesianAxis.yAxis populated for tests reading the legacy slice shape. */
		ctx?.setStore("cartesianAxis", "yAxis", String(s.id), s)
		prevSettings = s
	})

	onCleanup(() => {
		if (prevSettings) {
			const strId = String(prevSettings.id)
			/* eslint-disable-next-line solid/reactivity -- cleanup runs outside tracking; intentional */
			stateCtx?.setState("cartesianAxes", "yAxis", produce((axes) => { delete axes[strId] }))
			ctx?.setStore("cartesianAxis", "yAxis", produce((axes) => { delete axes[strId] }))
			prevSettings = null
		}
	})

	return null
}

function YAxisImpl(props: PropsWithDefaults) {
	let cartesianAxisRef: CartesianAxisRef | undefined
	let labelRef: SVGTextElement | null = null

	const ctx2 = useChartStore()
	const stateCtx2 = useContext(RechartsStateContext)
	const viewBox = useAxisViewBox
	const isPanorama = useIsPanorama()
	const axisType = "yAxis"
	const axisSize = createMemo((): Size | undefined =>
		ctx2 ? selectYAxisSize(ctx2.store, props.yAxisId) : undefined,
	)
	const position = createMemo(() =>
		ctx2 ? selectYAxisPosition(ctx2.store, props.yAxisId) : undefined,
	)
	const cartesianTickItems = createMemo(() =>
		ctx2 ? selectTicksOfAxis(ctx2.store, axisType, props.yAxisId, isPanorama) : undefined,
	)
	/*
	 * Here we select settings from the store and prefer to use them instead of the actual props
	 * so that the chart is consistent. If we used the props directly, some components will use axis settings
	 * from state and some from props and because there is a render step between these two, they might be showing different things.
	 * https://github.com/recharts/recharts/issues/6257
	 */
	const synchronizedSettings = createMemo(() =>
		ctx2 ? selectYAxisSettingsNoDefaults(ctx2.store, props.yAxisId) : undefined,
	)

	createEffect(() => {
		/* No dynamic width calculation is done when width !== 'auto'
		 * or when a function/react element is used for label */
		if (
			props.width !== "auto" ||
			!axisSize() ||
			isLabelContentAFunction(props.label) ||
			synchronizedSettings() == null
		) {
			return
		}

		if (!cartesianAxisRef) {
			return
		}

		const updatedYAxisWidth = cartesianAxisRef.getCalculatedWidth()
		const currentSize = axisSize()

		/* if the width has changed, update the width (with oscillation guard from legacy actions.updateYAxisWidth) */
		if (currentSize && Math.round(currentSize.width) !== Math.round(updatedYAxisWidth)) {
			const axisEntry = stateCtx2?.state.cartesianAxes.yAxis[String(props.yAxisId)]
			const axis = axisEntry?.settings
			if (axis != null) {
				const history = axis.widthHistory ?? []
				const skip =
					history.length === 3 &&
					history[0] === history[2] &&
					updatedYAxisWidth === history[1] &&
					updatedYAxisWidth !== axis.width &&
					Math.abs(updatedYAxisWidth - (history[0] ?? 0)) <= 1
				if (!skip) {
					const newHistory = [...history, updatedYAxisWidth].slice(-3)
					stateCtx2?.setState("cartesianAxes", "yAxis", String(props.yAxisId), "settings", {
						...axis,
						width: updatedYAxisWidth,
						widthHistory: newHistory,
					})
				}
			}
		}
	})

	/* resolved() drops when any dep is nullish; Show rerenders subtree when
	   the memo flips from falsy → truthy, matching upstream React semantics. */
	const resolved = createMemo(() => {
		const size = axisSize()
		const pos = position()
		const synced = synchronizedSettings()
		if (size == null || pos == null || synced == null) {
			return null
		}
		const { id: _del1, scale: _del2, ...restSynchronizedSettings } = synced
		return { pos, restSynchronizedSettings, size }
	})

	return (
		<Show when={resolved()}>
			{(v) => (
				<CartesianAxis
					{...props}
					{...v().restSynchronizedSettings}
					labelRef={labelRef}
					x={v().pos.x}
					y={v().pos.y}
					tickTextProps={props.width === "auto" ? { width: undefined } : { width: props.width }}
					width={v().size.width}
					height={v().size.height}
					class={clsx(`recharts-${axisType} ${axisType}`, props.class)}
					viewBox={viewBox()}
					ticks={cartesianTickItems()}
					axisType={axisType}
				/>
			)}
		</Show>
	)
}

export const yAxisDefaultProps = {
	allowDataOverflow: implicitYAxis.allowDataOverflow,
	allowDecimals: implicitYAxis.allowDecimals,
	allowDuplicatedCategory: implicitYAxis.allowDuplicatedCategory,
	angle: implicitYAxis.angle,
	axisLine: defaultCartesianAxisProps.axisLine,
	hide: false,
	includeHidden: implicitYAxis.includeHidden,
	interval: implicitYAxis.interval,
	label: false,
	minTickGap: implicitYAxis.minTickGap,
	mirror: implicitYAxis.mirror,
	orientation: implicitYAxis.orientation,
	padding: implicitYAxis.padding,
	reversed: implicitYAxis.reversed,
	scale: implicitYAxis.scale,
	tick: implicitYAxis.tick,
	tickCount: implicitYAxis.tickCount,
	tickLine: defaultCartesianAxisProps.tickLine,
	tickSize: defaultCartesianAxisProps.tickSize,
	type: implicitYAxis.type,
	width: implicitYAxis.width,
	yAxisId: 0,
} as const satisfies Partial<Props>

type PropsWithDefaults = RequiresDefaultProps<Props, typeof yAxisDefaultProps>

/**
 * @consumes CartesianViewBoxContext
 * @provides CartesianLabelContext
 */
export function YAxis(outsideProps: Props) {
	const props: PropsWithDefaults = resolveDefaultProps(outsideProps, yAxisDefaultProps)
	return (
		<>
			<SetYAxisSettings
				interval={props.interval}
				id={props.yAxisId}
				scale={props.scale}
				type={props.type}
				domain={props.domain}
				allowDataOverflow={props.allowDataOverflow}
				dataKey={props.dataKey}
				allowDuplicatedCategory={props.allowDuplicatedCategory}
				allowDecimals={props.allowDecimals}
				tickCount={props.tickCount}
				padding={props.padding}
				includeHidden={props.includeHidden}
				reversed={props.reversed}
				ticks={props.ticks}
				width={props.width}
				orientation={props.orientation}
				mirror={props.mirror}
				hide={props.hide}
				unit={props.unit}
				name={props.name}
				angle={props.angle}
				minTickGap={props.minTickGap}
				tick={
					typeof props.tick === "function"
						? (props.tick as (p: unknown) => JSX.Element)
						: props.tick
				}
				tickFormatter={props.tickFormatter}
			/>
			<YAxisImpl {...props} />
		</>
	)
}

YAxis.displayName = "YAxis"
