/**
 * Golden parity: the lookup-map svg filters must match the pre-map implementation byte for byte.
 * The old implementation (key lists, regex-free predicate chain) is copied below as the oracle.
 */
import { describe, expect, it } from "vitest"
import {
	camelizeSvgPropsForHandler,
	isSvgElementPropKey,
	svgPropertiesNoEvents,
} from "../../src/util/svgPropertiesNoEvents"
import { svgPropertiesAndEvents } from "../../src/util/svgPropertiesAndEvents"
import { isEventKey } from "../../src/util/excludeEventProps"

/* ── oracle: old implementation ─────────────────────────────────── */

const OLD_SVG_KEYS = [
	"aria-activedescendant",
	"aria-atomic",
	"aria-autocomplete",
	"aria-busy",
	"aria-checked",
	"aria-colcount",
	"aria-colindex",
	"aria-colspan",
	"aria-controls",
	"aria-current",
	"aria-describedby",
	"aria-details",
	"aria-disabled",
	"aria-errormessage",
	"aria-expanded",
	"aria-flowto",
	"aria-haspopup",
	"aria-hidden",
	"aria-invalid",
	"aria-keyshortcuts",
	"aria-label",
	"aria-labelledby",
	"aria-level",
	"aria-live",
	"aria-modal",
	"aria-multiline",
	"aria-multiselectable",
	"aria-orientation",
	"aria-owns",
	"aria-placeholder",
	"aria-posinset",
	"aria-pressed",
	"aria-readonly",
	"aria-relevant",
	"aria-required",
	"aria-roledescription",
	"aria-rowcount",
	"aria-rowindex",
	"aria-rowspan",
	"aria-selected",
	"aria-setsize",
	"aria-sort",
	"aria-valuemax",
	"aria-valuemin",
	"aria-valuenow",
	"aria-valuetext",
	"className",
	"color",
	"height",
	"id",
	"lang",
	"max",
	"media",
	"method",
	"min",
	"name",
	"style",
	/*
	 * removed 'type' SVGElementPropKey because we do not currently use any SVG elements
	 * that can use it, and it conflicts with the recharts prop 'type'
	 * https://github.com/recharts/recharts/pull/3327
	 * https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/type
	 */
	"target",
	"width",
	"role",
	"tabIndex",
	"accentHeight",
	"accumulate",
	"additive",
	"alignmentBaseline",
	"allowReorder",
	"alphabetic",
	"amplitude",
	"arabicForm",
	"ascent",
	"attributeName",
	"attributeType",
	"autoReverse",
	"azimuth",
	"baseFrequency",
	"baselineShift",
	"baseProfile",
	"bbox",
	"begin",
	"bias",
	"by",
	"calcMode",
	"capHeight",
	"clip",
	"clipPath",
	"clipPathUnits",
	"clipRule",
	"colorInterpolation",
	"colorInterpolationFilters",
	"colorProfile",
	"colorRendering",
	"contentScriptType",
	"contentStyleType",
	"cursor",
	"cx",
	"cy",
	"d",
	"decelerate",
	"descent",
	"diffuseConstant",
	"direction",
	"display",
	"divisor",
	"dominantBaseline",
	"dur",
	"dx",
	"dy",
	"edgeMode",
	"elevation",
	"enableBackground",
	"end",
	"exponent",
	"externalResourcesRequired",
	"fill",
	"fill-opacity",
	"fillOpacity",
	"fill-rule",
	"fillRule",
	"filter",
	"filterRes",
	"filterUnits",
	"floodColor",
	"floodOpacity",
	"focusable",
	"fontFamily",
	"fontSize",
	"fontSizeAdjust",
	"fontStretch",
	"fontStyle",
	"fontVariant",
	"fontWeight",
	"format",
	"from",
	"fx",
	"fy",
	"g1",
	"g2",
	"glyphName",
	"glyphOrientationHorizontal",
	"glyphOrientationVertical",
	"glyphRef",
	"gradientTransform",
	"gradientUnits",
	"hanging",
	"horizAdvX",
	"horizOriginX",
	"href",
	"ideographic",
	"imageRendering",
	"in2",
	"in",
	"intercept",
	"k1",
	"k2",
	"k3",
	"k4",
	"k",
	"kernelMatrix",
	"kernelUnitLength",
	"kerning",
	"keyPoints",
	"keySplines",
	"keyTimes",
	"lengthAdjust",
	"letterSpacing",
	"lightingColor",
	"limitingConeAngle",
	"local",
	"markerEnd",
	"markerHeight",
	"markerMid",
	"markerStart",
	"markerUnits",
	"markerWidth",
	"mask",
	"maskContentUnits",
	"maskUnits",
	"mathematical",
	"mode",
	"numOctaves",
	"offset",
	"opacity",
	"operator",
	"order",
	"orient",
	"orientation",
	"origin",
	"overflow",
	"overlinePosition",
	"overlineThickness",
	"paintOrder",
	"panose1",
	"pathLength",
	"patternContentUnits",
	"patternTransform",
	"patternUnits",
	"pointerEvents",
	"pointsAtX",
	"pointsAtY",
	"pointsAtZ",
	"preserveAlpha",
	"preserveAspectRatio",
	"primitiveUnits",
	"r",
	"radius",
	"refX",
	"refY",
	"renderingIntent",
	"repeatCount",
	"repeatDur",
	"requiredExtensions",
	"requiredFeatures",
	"restart",
	"result",
	"rotate",
	"rx",
	"ry",
	"seed",
	"shapeRendering",
	"slope",
	"spacing",
	"specularConstant",
	"specularExponent",
	"speed",
	"spreadMethod",
	"startOffset",
	"stdDeviation",
	"stemh",
	"stemv",
	"stitchTiles",
	"stopColor",
	"stopOpacity",
	"strikethroughPosition",
	"strikethroughThickness",
	"string",
	"stroke",
	"strokeDasharray",
	"strokeDashoffset",
	"strokeLinecap",
	"strokeLinejoin",
	"strokeMiterlimit",
	"strokeOpacity",
	"stroke-width",
	"strokeWidth",
	"surfaceScale",
	"systemLanguage",
	"tableValues",
	"targetX",
	"targetY",
	"textAnchor",
	"textDecoration",
	"textLength",
	"textRendering",
	"to",
	"transform",
	"u1",
	"u2",
	"underlinePosition",
	"underlineThickness",
	"unicode",
	"unicodeBidi",
	"unicodeRange",
	"unitsPerEm",
	"vAlphabetic",
	"values",
	"vectorEffect",
	"version",
	"vertAdvY",
	"vertOriginX",
	"vertOriginY",
	"vHanging",
	"vIdeographic",
	"viewTarget",
	"visibility",
	"vMathematical",
	"widths",
	"wordSpacing",
	"writingMode",
	"x1",
	"x2",
	"x",
	"xChannelSelector",
	"xHeight",
	"xlinkActuate",
	"xlinkArcrole",
	"xlinkHref",
	"xlinkRole",
	"xlinkShow",
	"xlinkTitle",
	"xlinkType",
	"xmlBase",
	"xmlLang",
	"xmlns",
	"xmlnsXlink",
	"xmlSpace",
	"y1",
	"y2",
	"y",
	"yChannelSelector",
	"z",
	"zoomAndPan",
	"ref",
	"angle",
]

const OLD_EVENT_KEYS = [
	"dangerouslySetInnerHTML",
	"onCopy",
	"onCopyCapture",
	"onCut",
	"onCutCapture",
	"onPaste",
	"onPasteCapture",
	"onCompositionEnd",
	"onCompositionEndCapture",
	"onCompositionStart",
	"onCompositionStartCapture",
	"onCompositionUpdate",
	"onCompositionUpdateCapture",
	"onFocus",
	"onFocusCapture",
	"onBlur",
	"onBlurCapture",
	"onChange",
	"onChangeCapture",
	"onBeforeInput",
	"onBeforeInputCapture",
	"onInput",
	"onInputCapture",
	"onReset",
	"onResetCapture",
	"onSubmit",
	"onSubmitCapture",
	"onInvalid",
	"onInvalidCapture",
	"onLoad",
	"onLoadCapture",
	"onError",
	"onErrorCapture",
	"onKeyDown",
	"onKeyDownCapture",
	"onKeyPress",
	"onKeyPressCapture",
	"onKeyUp",
	"onKeyUpCapture",
	"onAbort",
	"onAbortCapture",
	"onCanPlay",
	"onCanPlayCapture",
	"onCanPlayThrough",
	"onCanPlayThroughCapture",
	"onDurationChange",
	"onDurationChangeCapture",
	"onEmptied",
	"onEmptiedCapture",
	"onEncrypted",
	"onEncryptedCapture",
	"onEnded",
	"onEndedCapture",
	"onLoadedData",
	"onLoadedDataCapture",
	"onLoadedMetadata",
	"onLoadedMetadataCapture",
	"onLoadStart",
	"onLoadStartCapture",
	"onPause",
	"onPauseCapture",
	"onPlay",
	"onPlayCapture",
	"onPlaying",
	"onPlayingCapture",
	"onProgress",
	"onProgressCapture",
	"onRateChange",
	"onRateChangeCapture",
	"onSeeked",
	"onSeekedCapture",
	"onSeeking",
	"onSeekingCapture",
	"onStalled",
	"onStalledCapture",
	"onSuspend",
	"onSuspendCapture",
	"onTimeUpdate",
	"onTimeUpdateCapture",
	"onVolumeChange",
	"onVolumeChangeCapture",
	"onWaiting",
	"onWaitingCapture",
	"onAuxClick",
	"onAuxClickCapture",
	"onClick",
	"onClickCapture",
	"onContextMenu",
	"onContextMenuCapture",
	"onDoubleClick",
	"onDoubleClickCapture",
	"onDrag",
	"onDragCapture",
	"onDragEnd",
	"onDragEndCapture",
	"onDragEnter",
	"onDragEnterCapture",
	"onDragExit",
	"onDragExitCapture",
	"onDragLeave",
	"onDragLeaveCapture",
	"onDragOver",
	"onDragOverCapture",
	"onDragStart",
	"onDragStartCapture",
	"onDrop",
	"onDropCapture",
	"onMouseDown",
	"onMouseDownCapture",
	"onMouseEnter",
	"onMouseLeave",
	"onMouseMove",
	"onMouseMoveCapture",
	"onMouseOut",
	"onMouseOutCapture",
	"onMouseOver",
	"onMouseOverCapture",
	"onMouseUp",
	"onMouseUpCapture",
	"onSelect",
	"onSelectCapture",
	"onTouchCancel",
	"onTouchCancelCapture",
	"onTouchEnd",
	"onTouchEndCapture",
	"onTouchMove",
	"onTouchMoveCapture",
	"onTouchStart",
	"onTouchStartCapture",
	"onPointerDown",
	"onPointerDownCapture",
	"onPointerMove",
	"onPointerMoveCapture",
	"onPointerUp",
	"onPointerUpCapture",
	"onPointerCancel",
	"onPointerCancelCapture",
	"onPointerEnter",
	"onPointerEnterCapture",
	"onPointerLeave",
	"onPointerLeaveCapture",
	"onPointerOver",
	"onPointerOverCapture",
	"onPointerOut",
	"onPointerOutCapture",
	"onGotPointerCapture",
	"onGotPointerCaptureCapture",
	"onLostPointerCapture",
	"onLostPointerCaptureCapture",
	"onScroll",
	"onScrollCapture",
	"onWheel",
	"onWheelCapture",
	"onAnimationStart",
	"onAnimationStartCapture",
	"onAnimationEnd",
	"onAnimationEndCapture",
	"onAnimationIteration",
	"onAnimationIterationCapture",
	"onTransitionEnd",
	"onTransitionEndCapture",
]

const OLD_CAMEL_TO_KEBAB = new Map<string, string>([
	["accentHeight", "accent-height"],
	["alignmentBaseline", "alignment-baseline"],
	["arabicForm", "arabic-form"],
	["baselineShift", "baseline-shift"],
	["capHeight", "cap-height"],
	["clipPath", "clip-path"],
	["clipPathUnits", "clipPathUnits"],
	["clipRule", "clip-rule"],
	["colorInterpolation", "color-interpolation"],
	["colorInterpolationFilters", "color-interpolation-filters"],
	["colorProfile", "color-profile"],
	["colorRendering", "color-rendering"],
	["dominantBaseline", "dominant-baseline"],
	["enableBackground", "enable-background"],
	["fillOpacity", "fill-opacity"],
	["fillRule", "fill-rule"],
	["floodColor", "flood-color"],
	["floodOpacity", "flood-opacity"],
	["fontFamily", "font-family"],
	["fontSize", "font-size"],
	["fontSizeAdjust", "font-size-adjust"],
	["fontStretch", "font-stretch"],
	["fontStyle", "font-style"],
	["fontVariant", "font-variant"],
	["fontWeight", "font-weight"],
	["glyphName", "glyph-name"],
	["glyphOrientationHorizontal", "glyph-orientation-horizontal"],
	["glyphOrientationVertical", "glyph-orientation-vertical"],
	["horizAdvX", "horiz-adv-x"],
	["horizOriginX", "horiz-origin-x"],
	["imageRendering", "image-rendering"],
	["letterSpacing", "letter-spacing"],
	["lightingColor", "lighting-color"],
	["markerEnd", "marker-end"],
	["markerMid", "marker-mid"],
	["markerStart", "marker-start"],
	["overlinePosition", "overline-position"],
	["overlineThickness", "overline-thickness"],
	["paintOrder", "paint-order"],
	["panose1", "panose-1"],
	["pointerEvents", "pointer-events"],
	["renderingIntent", "rendering-intent"],
	["shapeRendering", "shape-rendering"],
	["stopColor", "stop-color"],
	["stopOpacity", "stop-opacity"],
	["strikethroughPosition", "strikethrough-position"],
	["strikethroughThickness", "strikethrough-thickness"],
	["strokeDasharray", "stroke-dasharray"],
	["strokeDashoffset", "stroke-dashoffset"],
	["strokeLinecap", "stroke-linecap"],
	["strokeLinejoin", "stroke-linejoin"],
	["strokeMiterlimit", "stroke-miterlimit"],
	["strokeOpacity", "stroke-opacity"],
	["strokeWidth", "stroke-width"],
	["textAnchor", "text-anchor"],
	["textDecoration", "text-decoration"],
	["textRendering", "text-rendering"],
	["underlinePosition", "underline-position"],
	["underlineThickness", "underline-thickness"],
	["unicodeBidi", "unicode-bidi"],
	["unicodeRange", "unicode-range"],
	["unitsPerEm", "units-per-em"],
	["vAlphabetic", "v-alphabetic"],
	["vectorEffect", "vector-effect"],
	["vertAdvY", "vert-adv-y"],
	["vertOriginX", "vert-origin-x"],
	["vertOriginY", "vert-origin-y"],
	["vHanging", "v-hanging"],
	["vIdeographic", "v-ideographic"],
	["vMathematical", "v-mathematical"],
	["wordSpacing", "word-spacing"],
	["writingMode", "writing-mode"],
	["xHeight", "x-height"],
	/* HTML/SVG focus + a11y attrs: when forwarded via spread (`{...attrs}`),
	 * Solid writes the key verbatim via `setAttribute`. Browsers parse HTML
	 * attrs case-insensitively but `getAttribute("tabindex")` matches exactly
	 * the stored name — and tests assert the lowercase form. */
	["tabIndex", "tabindex"],
	["readOnly", "readonly"],
	["contentEditable", "contenteditable"],
	["spellCheck", "spellcheck"],
	["autoFocus", "autofocus"],
])

const oldSvgKeySet = new Set<string>(OLD_SVG_KEYS)
const oldKebabKeySet = new Set<string>(OLD_CAMEL_TO_KEBAB.values())
const oldIsSvgKey = (key: PropertyKey) =>
	typeof key === "string" && (oldSvgKeySet.has(key) || oldKebabKeySet.has(key))
const oldIsData = (key: PropertyKey) => typeof key === "string" && key.startsWith("data-")
const oldCanonical = (key: string) => OLD_CAMEL_TO_KEBAB.get(key) ?? key
const oldIsEventKey = (key: PropertyKey) => typeof key === "string" && (OLD_EVENT_KEYS as string[]).includes(key)

function oldNoEvents(obj: Record<string, unknown>): Record<string, unknown> {
	const result: Record<string, unknown> = {}
	for (const key in obj) {
		if (Object.prototype.hasOwnProperty.call(obj, key)) {
			if (oldIsSvgKey(key) || oldIsData(key)) result[oldCanonical(key)] = obj[key]
		}
	}
	return result
}

function oldAndEvents(obj: Record<string, unknown>): Record<string, unknown> {
	const result: Record<string, unknown> = {}
	for (const key in obj) {
		if (Object.prototype.hasOwnProperty.call(obj, key)) {
			if (oldIsSvgKey(key) || oldIsData(key)) result[oldCanonical(key)] = obj[key]
			else if (oldIsEventKey(key)) result[key] = obj[key]
		}
	}
	return result
}

const oldKebabToCamel = new Map<string, string>()
for (const [camel, kebab] of OLD_CAMEL_TO_KEBAB) if (camel !== kebab) oldKebabToCamel.set(kebab, camel)
oldKebabToCamel.set("class", "className")

function oldCamelize(obj: Record<string, unknown>): Record<string, unknown> {
	const out: Record<string, unknown> = {}
	for (const key in obj) {
		if (Object.prototype.hasOwnProperty.call(obj, key)) out[oldKebabToCamel.get(key) ?? key] = obj[key]
	}
	return out
}

/* ── inputs: every known key in camel and kebab form, plus extras ── */

const kebabize = (key: string) => key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)
const allKeys = Array.from(
	new Set<string>([
		...OLD_SVG_KEYS,
		...OLD_SVG_KEYS.map(kebabize),
		...OLD_CAMEL_TO_KEBAB.keys(),
		...OLD_CAMEL_TO_KEBAB.values(),
		...OLD_EVENT_KEYS,
		...OLD_EVENT_KEYS.map((k) => k.toLowerCase()),
		"data-foo",
		"data-testid",
		"data-",
		"aria-label",
		"aria-hidden",
		"ariaLabel",
		"class",
		"className",
		"on",
		"onFoo",
		"once",
		"custom",
		"",
		"constructor",
		"toString",
		"__proto__x",
	]),
)
const input = Object.fromEntries(allKeys.map((key, i) => [key, i]))

describe("svgPropertiesNoEvents golden parity", () => {
	it("matches the old implementation for every key, in key order", () => {
		const expected = oldNoEvents(input)
		const actual = svgPropertiesNoEvents(input) as Record<string, unknown>
		expect(Object.keys(actual)).toEqual(Object.keys(expected))
		expect(actual).toEqual(expected)
	})

	it("svgPropertiesAndEvents matches the old implementation", () => {
		const expected = oldAndEvents(input)
		const actual = svgPropertiesAndEvents(input) as Record<string, unknown>
		expect(Object.keys(actual)).toEqual(Object.keys(expected))
		expect(actual).toEqual(expected)
	})

	it("camelizeSvgPropsForHandler matches the old implementation", () => {
		const expected = oldCamelize(input)
		const actual = camelizeSvgPropsForHandler(input)
		expect(Object.keys(actual)).toEqual(Object.keys(expected))
		expect(actual).toEqual(expected)
	})

	it("key predicates agree with the old implementation", () => {
		for (const key of allKeys) {
			expect(isSvgElementPropKey(key), key).toBe(oldIsSvgKey(key))
			expect(isEventKey(key), key).toBe(oldIsEventKey(key))
		}
		expect(isSvgElementPropKey(Symbol("x"))).toBe(false)
		expect(isEventKey(Symbol("x"))).toBe(false)
	})

	it("ignores inherited enumerable keys", () => {
		const proto = { fill: "red", "data-x": 1 }
		const obj = Object.assign(Object.create(proto), { stroke: "blue" })
		expect(svgPropertiesNoEvents(obj)).toEqual(oldNoEvents(obj))
		expect(svgPropertiesNoEvents(obj)).toEqual({ stroke: "blue" })
	})
})
