// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    /** The page component is a server function; its `$component` is delivered eagerly. */
    server?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/(docs)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(docs)")>;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/accordion/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/alert-dialog/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/autocomplete/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/avatar/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/button/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/checkbox-group/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/checkbox/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/collapsible/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/combobox/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/context-menu/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/dialog/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/drawer/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/field/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/fieldset/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/form/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/input/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/menu/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/menubar/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/meter/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/navigation-menu/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/number-field/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/otp-field/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/popover/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/preview-card/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/progress/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/radio/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/scroll-area/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/select/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/separator/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/slider/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/switch/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/tabs/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/toast/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/toggle-group/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/toggle/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/toolbar/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/components/tooltip/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/handbook/animation/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/handbook/composition/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/handbook/customization/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/handbook/forms/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/handbook/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/handbook/styling/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/handbook/typescript/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/about/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/accessibility/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/community/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/quick-start/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-alpha-4/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-alpha-5/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-alpha-6/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-alpha-7/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-alpha-8/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-beta-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-beta-1/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-beta-2/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-beta-3/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-beta-4/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-beta-5/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-beta-6/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-beta-7/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-rc-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-rc-1/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0-rc-2/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-0-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-1-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-2-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-3-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-4-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-4-1/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-5-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-6-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-7-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/overview/releases/v1-8-0/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/utils/csp-provider/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/utils/direction-provider/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/utils/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/utils/merge-props/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/(docs)/solid/utils/use-render/";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
    },
    {
      path: "/mdx-test";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/";
      id: "/(docs)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(docs)")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/solid/";
          id: "/solid/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/utils/";
          id: "/solid/utils/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/handbook/";
          id: "/solid/handbook/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/";
          id: "/solid/overview/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/";
          id: "/solid/components/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/handbook/forms/";
          id: "/solid/handbook/forms/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/about/";
          id: "/solid/overview/about/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/form/";
          id: "/solid/components/form/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/menu/";
          id: "/solid/components/menu/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/tabs/";
          id: "/solid/components/tabs/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/field/";
          id: "/solid/components/field/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/input/";
          id: "/solid/components/input/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/meter/";
          id: "/solid/components/meter/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/radio/";
          id: "/solid/components/radio/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/toast/";
          id: "/solid/components/toast/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/handbook/styling/";
          id: "/solid/handbook/styling/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/utils/use-render/";
          id: "/solid/utils/use-render/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/avatar/";
          id: "/solid/components/avatar/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/button/";
          id: "/solid/components/button/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/dialog/";
          id: "/solid/components/dialog/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/drawer/";
          id: "/solid/components/drawer/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/select/";
          id: "/solid/components/select/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/slider/";
          id: "/solid/components/slider/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/switch/";
          id: "/solid/components/switch/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/toggle/";
          id: "/solid/components/toggle/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/";
          id: "/solid/overview/releases/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/utils/merge-props/";
          id: "/solid/utils/merge-props/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/menubar/";
          id: "/solid/components/menubar/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/popover/";
          id: "/solid/components/popover/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/toolbar/";
          id: "/solid/components/toolbar/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/tooltip/";
          id: "/solid/components/tooltip/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/handbook/animation/";
          id: "/solid/handbook/animation/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/community/";
          id: "/solid/overview/community/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/utils/csp-provider/";
          id: "/solid/utils/csp-provider/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/checkbox/";
          id: "/solid/components/checkbox/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/combobox/";
          id: "/solid/components/combobox/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/fieldset/";
          id: "/solid/components/fieldset/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/progress/";
          id: "/solid/components/progress/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/handbook/typescript/";
          id: "/solid/handbook/typescript/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/accordion/";
          id: "/solid/components/accordion/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/otp-field/";
          id: "/solid/components/otp-field/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/separator/";
          id: "/solid/components/separator/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/handbook/composition/";
          id: "/solid/handbook/composition/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/quick-start/";
          id: "/solid/overview/quick-start/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/collapsible/";
          id: "/solid/components/collapsible/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/scroll-area/";
          id: "/solid/components/scroll-area/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/handbook/customization/";
          id: "/solid/handbook/customization/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/accessibility/";
          id: "/solid/overview/accessibility/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/alert-dialog/";
          id: "/solid/components/alert-dialog/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/autocomplete/";
          id: "/solid/components/autocomplete/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/context-menu/";
          id: "/solid/components/context-menu/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/number-field/";
          id: "/solid/components/number-field/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/preview-card/";
          id: "/solid/components/preview-card/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/toggle-group/";
          id: "/solid/components/toggle-group/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0/";
          id: "/solid/overview/releases/v1-0-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-1-0/";
          id: "/solid/overview/releases/v1-1-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-2-0/";
          id: "/solid/overview/releases/v1-2-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-3-0/";
          id: "/solid/overview/releases/v1-3-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-4-0/";
          id: "/solid/overview/releases/v1-4-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-4-1/";
          id: "/solid/overview/releases/v1-4-1/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-5-0/";
          id: "/solid/overview/releases/v1-5-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-6-0/";
          id: "/solid/overview/releases/v1-6-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-7-0/";
          id: "/solid/overview/releases/v1-7-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-8-0/";
          id: "/solid/overview/releases/v1-8-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/utils/direction-provider/";
          id: "/solid/utils/direction-provider/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/checkbox-group/";
          id: "/solid/components/checkbox-group/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/components/navigation-menu/";
          id: "/solid/components/navigation-menu/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-rc-0/";
          id: "/solid/overview/releases/v1-0-0-rc-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-rc-1/";
          id: "/solid/overview/releases/v1-0-0-rc-1/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-rc-2/";
          id: "/solid/overview/releases/v1-0-0-rc-2/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-beta-0/";
          id: "/solid/overview/releases/v1-0-0-beta-0/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-beta-1/";
          id: "/solid/overview/releases/v1-0-0-beta-1/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-beta-2/";
          id: "/solid/overview/releases/v1-0-0-beta-2/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-beta-3/";
          id: "/solid/overview/releases/v1-0-0-beta-3/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-beta-4/";
          id: "/solid/overview/releases/v1-0-0-beta-4/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-beta-5/";
          id: "/solid/overview/releases/v1-0-0-beta-5/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-beta-6/";
          id: "/solid/overview/releases/v1-0-0-beta-6/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-beta-7/";
          id: "/solid/overview/releases/v1-0-0-beta-7/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-alpha-4/";
          id: "/solid/overview/releases/v1-0-0-alpha-4/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-alpha-5/";
          id: "/solid/overview/releases/v1-0-0-alpha-5/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-alpha-6/";
          id: "/solid/overview/releases/v1-0-0-alpha-6/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-alpha-7/";
          id: "/solid/overview/releases/v1-0-0-alpha-7/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/solid/overview/releases/v1-0-0-alpha-8/";
          id: "/solid/overview/releases/v1-0-0-alpha-8/";
          page: true;
          $component: FileRouteLazyRef;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/mdx-test";
      id: "/mdx-test";
      page: true;
      $component: FileRouteLazyRef;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
